-- =============================================
-- DATASET: CUSTOMER DATABASE (BRONZE LAYER)
-- OWNER: CUSTOMER DOMAIN (DEV B)
-- =============================================
-- Run this file in the Supabase SQL Editor.
-- It is safe to run repeatedly.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- One row per raw customer file uploaded to Storage.
CREATE TABLE IF NOT EXISTS public.customer_batches (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    file_name text NOT NULL,
    file_path text NOT NULL UNIQUE,
    file_size_bytes bigint NOT NULL CHECK (file_size_bytes >= 0),
    row_count bigint CHECK (row_count IS NULL OR row_count >= 0),
    status text NOT NULL DEFAULT 'uploaded' CHECK (
        status IN (
            'uploaded',
            'processing',
            'ingested',
            'validation_failed',
            'ingestion_failed'
        )
    ),
    uploaded_by text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Structured, validated customer rows produced by the FastAPI engine.
-- Source column names intentionally match the CSV headers exactly.
CREATE TABLE IF NOT EXISTS public.bronze_customer_database (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CUSTOMER NUMBER" text NOT NULL UNIQUE,
    "GENDER" text,
    "BIRTHDAY" date,
    "AGE" integer CHECK ("AGE" IS NULL OR "AGE" >= 0),
    "CITY" text,
    "PROVINCE" text,
    "EXPIRY DATE" date,
    "MEMBER LOCATION" text,
    "APPLICATION DATE" date,
    "MEMBER SINCE" date,
    "LAST VISIT" date,
    "FREQUENCY OF VISIT" integer CHECK (
        "FREQUENCY OF VISIT" IS NULL OR "FREQUENCY OF VISIT" >= 0
    ),
    "LAST VISITED STORE" text,
    source_batch_id uuid NOT NULL REFERENCES public.customer_batches(id),
    loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_batches_created_at
    ON public.customer_batches (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_batches_status
    ON public.customer_batches (status);
CREATE INDEX IF NOT EXISTS idx_bronze_customer_city
    ON public.bronze_customer_database ("CITY");
CREATE INDEX IF NOT EXISTS idx_bronze_customer_province
    ON public.bronze_customer_database ("PROVINCE");
CREATE INDEX IF NOT EXISTS idx_bronze_customer_last_visit
    ON public.bronze_customer_database ("LAST VISIT");
CREATE INDEX IF NOT EXISTS idx_bronze_customer_source_batch
    ON public.bronze_customer_database (source_batch_id);

ALTER TABLE public.customer_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bronze_customer_database ENABLE ROW LEVEL SECURITY;

-- The authenticated frontend uploads files and creates pending batch metadata.
DROP POLICY IF EXISTS "customer_batches_authenticated_select"
    ON public.customer_batches;
CREATE POLICY "customer_batches_authenticated_select"
    ON public.customer_batches
    FOR SELECT TO authenticated
    USING (true);

DROP POLICY IF EXISTS "customer_batches_authenticated_insert"
    ON public.customer_batches;
CREATE POLICY "customer_batches_authenticated_insert"
    ON public.customer_batches
    FOR INSERT TO authenticated
    WITH CHECK (auth.uid() IS NOT NULL);

-- The frontend may read Bronze rows. Only the service-role backend writes them.
DROP POLICY IF EXISTS "bronze_customer_authenticated_select"
    ON public.bronze_customer_database;
CREATE POLICY "bronze_customer_authenticated_select"
    ON public.bronze_customer_database
    FOR SELECT TO authenticated
    USING (true);

NOTIFY pgrst, 'reload schema';
