-- Customer database batch tracking and Bronze storage.
CREATE TABLE IF NOT EXISTS customer_batches (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    file_name text NOT NULL,
    file_path text NOT NULL UNIQUE,
    file_size_bytes bigint NOT NULL,
    row_count bigint,
    status text NOT NULL DEFAULT 'uploaded',
    uploaded_by text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bronze_customer_database (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CUSTOMER_NUMBER" text NOT NULL,
    "GENDER" text,
    "BIRTHDAY" text,
    "AGE" text,
    "CITY" text,
    "PROVINCE" text,
    "EXPIRY_DATE" text,
    "MEMBER_LOCATION" text,
    "APPLICATION_DATE" text,
    "MEMBER_SINCE" text,
    "LAST_VISIT" text,
    "FREQUENCY_OF_VISIT" text,
    "LAST_VISITED_STORE" text,
    source_batch_id uuid NOT NULL REFERENCES customer_batches(id),
    loaded_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE ("CUSTOMER_NUMBER")
);

CREATE INDEX IF NOT EXISTS idx_bronze_customer_city ON bronze_customer_database ("CITY");
CREATE INDEX IF NOT EXISTS idx_bronze_customer_province ON bronze_customer_database ("PROVINCE");
CREATE INDEX IF NOT EXISTS idx_bronze_customer_batch ON bronze_customer_database (source_batch_id);

ALTER TABLE customer_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE bronze_customer_database ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read customer batches"
ON customer_batches FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can create customer batches"
ON customer_batches FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read customer bronze data"
ON bronze_customer_database FOR SELECT TO authenticated USING (true);
