-- =============================================
-- DATASET: CUSTOMER DATABASE (SILVER LAYER)
-- OWNER: CUSTOMER DOMAIN (DEV B)
-- =============================================
-- Run this file in the Supabase SQL Editor.
-- It is safe to run repeatedly.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- One Silver row corresponds to exactly one immutable Bronze row. Invalid raw
-- values become NULL in their typed column and are explained by quality_issues.
CREATE TABLE IF NOT EXISTS public.silver_customer_database (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bronze_id bigint NOT NULL UNIQUE
        REFERENCES public.bronze_customer_database(id),
    source_batch_id uuid NOT NULL
        REFERENCES public.customer_batches(id),
    "CUSTOMER NUMBER" text NOT NULL,
    "GENDER" text,
    "BIRTHDAY" date,
    "AGE" integer,
    "CITY" text,
    "PROVINCE" text,
    "EXPIRY DATE" date,
    "MEMBER LOCATION" text,
    "APPLICATION DATE" date,
    "MEMBER SINCE" date,
    "LAST VISIT" date,
    "FREQUENCY OF VISIT" integer,
    "LAST VISITED STORE" text,
    anomaly_class text NOT NULL DEFAULT '0'
        CONSTRAINT silver_customer_anomaly_class_check CHECK (
        anomaly_class IN ('0', '1A', '1B')
    ),
    validation_status text NOT NULL DEFAULT 'clean' CHECK (
        validation_status IN ('clean', 'flagged', 'resolved')
    ),
    quality_issues text[] NOT NULL DEFAULT ARRAY[]::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Migrates Silver tables created before anomaly classes were introduced.
ALTER TABLE public.silver_customer_database
    ADD COLUMN IF NOT EXISTS anomaly_class text NOT NULL DEFAULT '0';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.silver_customer_database'::regclass
          AND conname = 'silver_customer_anomaly_class_check'
    ) THEN
        ALTER TABLE public.silver_customer_database
            ADD CONSTRAINT silver_customer_anomaly_class_check
            CHECK (anomaly_class IN ('0', '1A', '1B'));
    END IF;
END
$$;

-- Tracks asynchronous Bronze-to-Silver processing without changing Bronze
-- batch statuses. Only one active Customer Silver run should be started at a
-- time by the backend.
CREATE TABLE IF NOT EXISTS public.customer_silver_runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    status text NOT NULL DEFAULT 'queued' CHECK (
        status IN ('queued', 'processing', 'completed', 'failed')
    ),
    source_row_count bigint,
    processed_row_count bigint,
    clean_row_count bigint,
    flagged_row_count bigint,
    error_message text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_silver_customer_number
    ON public.silver_customer_database ("CUSTOMER NUMBER");
CREATE INDEX IF NOT EXISTS idx_silver_customer_source_batch
    ON public.silver_customer_database (source_batch_id);
CREATE INDEX IF NOT EXISTS idx_silver_customer_validation_status
    ON public.silver_customer_database (validation_status);
CREATE INDEX IF NOT EXISTS idx_silver_customer_anomaly_class
    ON public.silver_customer_database (anomaly_class);
CREATE INDEX IF NOT EXISTS idx_silver_customer_city
    ON public.silver_customer_database ("CITY");
CREATE INDEX IF NOT EXISTS idx_silver_customer_province
    ON public.silver_customer_database ("PROVINCE");
CREATE INDEX IF NOT EXISTS idx_customer_silver_runs_created_at
    ON public.customer_silver_runs (created_at DESC);

ALTER TABLE public.silver_customer_database ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_silver_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "silver_customer_authenticated_select"
    ON public.silver_customer_database;
CREATE POLICY "silver_customer_authenticated_select"
    ON public.silver_customer_database
    FOR SELECT TO authenticated
    USING (true);

DROP POLICY IF EXISTS "customer_silver_runs_authenticated_select"
    ON public.customer_silver_runs;
CREATE POLICY "customer_silver_runs_authenticated_select"
    ON public.customer_silver_runs
    FOR SELECT TO authenticated
    USING (true);

NOTIFY pgrst, 'reload schema';
