-- ==========================================
-- DATASET: SKU HIERARCHY (SILVER LAYER)
-- Phase 1: tables for pipeline runs, tagged output,
-- exclusions, and append-only anomaly resolutions
-- ==========================================

-- One row per silver pipeline run (what the frontend polls)
CREATE TABLE IF NOT EXISTS silver_sku_batches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    source_bronze_batch_id UUID,
    status VARCHAR(50) DEFAULT 'processing',      -- processing | completed | failed
    step TEXT,                                    -- live progress text
    silver_row_count INTEGER,
    excluded_row_count INTEGER,
    error_message TEXT,
    started_by VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);
ALTER TABLE silver_sku_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON silver_sku_batches FOR ALL USING (true) WITH CHECK (true);

-- NB3 tagged output (populated in Phase 2)
CREATE TABLE IF NOT EXISTS silver_sku_hierarchy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SKU_CODE" TEXT,
    "SKU_DESCRIPTION" TEXT,
    "DIVISION" TEXT,
    "DEPARTMENT" TEXT,
    "CATEGORY" TEXT,
    "CLASS" TEXT,
    "BRAND" TEXT,
    "STANDARD_PACK" TEXT,
    "PACK_TYPE" TEXT,
    "BUY_UNIT_OF_MEASURE" TEXT,
    "SELL_UNIT_OF_MEASURE" TEXT,
    "UNIT_COST" TEXT,
    "WEIGTH" TEXT,
    "HEIGHT" TEXT,
    "LENGTH" TEXT,
    "WIDTH" TEXT,
    "CUBE" TEXT,
    "VENDOR_CODE" TEXT,
    "VENDOR_DESCRIPTION" TEXT,
    -- pipeline-derived columns (exact set finalized in Phase 2 to match NB3 output)
    "NORM_DESCRIPTION" TEXT,
    "EXTRACTED_BRAND" TEXT,
    "EXTRACTED_UNITS" TEXT,
    "EXTRACTED_PACK" TEXT,
    "IS_PROMO" TEXT,
    "DESC_BASE" TEXT,
    "DUP_FAMILY_ID" TEXT,
    "VARIANT_FAMILY_ID" TEXT,
    "PROMO_FAMILY_ID" TEXT,
    "FAMILY_OVERLAP" TEXT,
    "ANOMALY_TAGS" TEXT,                          -- pipe-delimited, as emitted by NB3
    silver_batch_id UUID REFERENCES silver_sku_batches(id),
    loaded_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_silver_sku_code ON silver_sku_hierarchy ("SKU_CODE");
CREATE INDEX idx_silver_sku_anomaly ON silver_sku_hierarchy ("ANOMALY_TAGS");
CREATE INDEX idx_silver_sku_dupfam ON silver_sku_hierarchy ("DUP_FAMILY_ID");
CREATE INDEX idx_silver_sku_varfam ON silver_sku_hierarchy ("VARIANT_FAMILY_ID");
CREATE INDEX idx_silver_sku_promofam ON silver_sku_hierarchy ("PROMO_FAMILY_ID");
CREATE INDEX idx_silver_sku_batch ON silver_sku_hierarchy (silver_batch_id);
ALTER TABLE silver_sku_hierarchy ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON silver_sku_hierarchy FOR ALL USING (true) WITH CHECK (true);

-- NB2 exclusions (purged/bucket/null-desc etc.) — read-only reference,
-- also the lookup for the future DROPPED_SKU_TRANSACTION relational flag
CREATE TABLE IF NOT EXISTS silver_sku_excluded (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SKU_CODE" TEXT,
    "SKU_DESCRIPTION" TEXT,
    "DIVISION" TEXT,
    "DEPARTMENT" TEXT,
    "CATEGORY" TEXT,
    "CLASS" TEXT,
    "BRAND" TEXT,
    "ANOMALY_TAG" TEXT,
    "ANOMALY_REMARKS" TEXT,
    silver_batch_id UUID REFERENCES silver_sku_batches(id),
    loaded_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_silver_excluded_sku_code ON silver_sku_excluded ("SKU_CODE");
CREATE INDEX idx_silver_excluded_tag ON silver_sku_excluded ("ANOMALY_TAG");
ALTER TABLE silver_sku_excluded ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON silver_sku_excluded FOR ALL USING (true) WITH CHECK (true);

-- Append-only resolution log: one record per family decision.
-- Never mutates silver rows; superseding record = undo.
CREATE TABLE IF NOT EXISTS sku_anomaly_resolutions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    silver_batch_id UUID REFERENCES silver_sku_batches(id),
    family_id TEXT NOT NULL,                      -- e.g. DUP-0003643
    family_type VARCHAR(20) NOT NULL,             -- DUP | VARIANT | PROMO
    action VARCHAR(50) NOT NULL,                  -- merge | confirm_variants | link_promo | keep | exclude
    canonical_sku_code TEXT,
    affected_sku_codes TEXT[],
    remarks TEXT,
    resolved_by VARCHAR(255),
    resolved_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_resolutions_family ON sku_anomaly_resolutions (family_id);
CREATE INDEX idx_resolutions_batch ON sku_anomaly_resolutions (silver_batch_id);
ALTER TABLE sku_anomaly_resolutions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON sku_anomaly_resolutions FOR ALL USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload schema';
