-- ==========================================
-- DATASET: SKU HIERARCHY (BRONZE LAYER)
-- OWNER: SKU HIERARCHY TEAM
-- ==========================================
-- Record of DDL executed in the Supabase SQL Editor.
-- Bronze holds raw, schema-validated data as text.
-- Type casting and cleaning happen in the Silver layer.

CREATE TABLE IF NOT EXISTS sku_batches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    file_name VARCHAR(255),
    file_path TEXT,
    file_size_bytes BIGINT,
    uploaded_by VARCHAR(255),
    status VARCHAR(255),
    row_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE sku_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated insert to sku_batches" ON sku_batches FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated read to sku_batches" ON sku_batches FOR SELECT TO authenticated USING (true);

CREATE TABLE IF NOT EXISTS bronze_sku_hierarchy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SKU_CODE" TEXT,
    "SKU_DESCRIPTION" TEXT,
    "DIVISION" TEXT,
    "DEPARTMENT" TEXT,
    "CATEGORY" TEXT,
    "CLASS" TEXT,
    "BRAND" TEXT,
    "STANDARD_PACK" TEXT,
    "PACK_TYPE" TEXT,
    "BUY_UNIT_OF_MEASURE" TEXT,
    "SELL_UNIT_OF_MEASURE" TEXT,
    "UNIT_COST" TEXT,
    "WEIGTH" TEXT,          -- intentionally matches source misspelling
    "HEIGHT" TEXT,
    "LENGTH" TEXT,
    "WIDTH" TEXT,
    "CUBE" TEXT,
    "VENDOR_CODE" TEXT,
    "VENDOR_DESCRIPTION" TEXT,
    source_batch_id TEXT,
    loaded_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX idx_bronze_sku_hierarchy_sku_code ON bronze_sku_hierarchy ("SKU_CODE");
CREATE INDEX idx_bronze_sku_hierarchy_division ON bronze_sku_hierarchy ("DIVISION");
CREATE INDEX idx_bronze_sku_hierarchy_source_batch_id ON bronze_sku_hierarchy (source_batch_id);
ALTER TABLE bronze_sku_hierarchy ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON bronze_sku_hierarchy FOR ALL USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload schema';

-- ==========================================
-- Migration 2: row_hash fingerprint for exact-duplicate detection
-- (already executed in Supabase SQL Editor)
-- ==========================================

ALTER TABLE bronze_sku_hierarchy
  ADD COLUMN row_hash TEXT GENERATED ALWAYS AS (
    md5(
      coalesce("SKU_CODE",'')             || '|' ||
      coalesce("SKU_DESCRIPTION",'')      || '|' ||
      coalesce("DIVISION",'')             || '|' ||
      coalesce("DEPARTMENT",'')           || '|' ||
      coalesce("CATEGORY",'')             || '|' ||
      coalesce("CLASS",'')                || '|' ||
      coalesce("BRAND",'')                || '|' ||
      coalesce("STANDARD_PACK",'')        || '|' ||
      coalesce("PACK_TYPE",'')            || '|' ||
      coalesce("BUY_UNIT_OF_MEASURE",'')  || '|' ||
      coalesce("SELL_UNIT_OF_MEASURE",'') || '|' ||
      coalesce("UNIT_COST",'')            || '|' ||
      coalesce("WEIGTH",'')               || '|' ||
      coalesce("HEIGHT",'')               || '|' ||
      coalesce("LENGTH",'')               || '|' ||
      coalesce("WIDTH",'')                || '|' ||
      coalesce("CUBE",'')                 || '|' ||
      coalesce("VENDOR_CODE",'')          || '|' ||
      coalesce("VENDOR_DESCRIPTION",'')
    )
  ) STORED;

CREATE UNIQUE INDEX uq_bronze_sku_hierarchy_row_hash ON bronze_sku_hierarchy (row_hash);

NOTIFY pgrst, 'reload schema';