"""
Run this in Supabase SQL Editor to create the Bronze table:

CREATE TABLE bronze_loyalty_sales (
    id bigint generated by default as identity primary key,
    "DATE" text,
    "TRANSACTION_NUMBER" text,
    "REGISTER_NUMBER" text,
    "STORE_CODE" text,
    "STORE_CATEGORIZATION" text,
    "CUSTOMER_NUMBER" text,
    "SKU_CODE" text,
    "TRANSACTION_TYPE" text,
    "LOYALTY_SALES" text,
    "QTY_SOLD" text,
    source_batch_id text,
    loaded_at timestamptz default now()
);

CREATE INDEX idx_bronze_loyalty_sales_date ON bronze_loyalty_sales ("DATE");
CREATE INDEX idx_bronze_loyalty_sales_store_code ON bronze_loyalty_sales ("STORE_CODE");
CREATE INDEX idx_bronze_loyalty_sales_sku_code ON bronze_loyalty_sales ("SKU_CODE");
CREATE INDEX idx_bronze_loyalty_sales_source_batch_id ON bronze_loyalty_sales (source_batch_id);

ALTER TABLE bronze_loyalty_sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations during pilot" ON bronze_loyalty_sales FOR ALL USING (true) WITH CHECK (true);
"""
import logging
from supabase import create_client, Client
from app.config import SUPABASE_URL, SUPABASE_SERVICE_KEY

logger = logging.getLogger(__name__)

if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
    raise ValueError("SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in the environment.")

_supabase_client: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

def get_client() -> Client:
    return _supabase_client

def download_file(bucket: str, path: str) -> bytes:
    try:
        return _supabase_client.storage.from_(bucket).download(path)
    except Exception as e:
        logger.error(f"Failed to download file {path} from bucket {bucket}: {e}")
        raise RuntimeError(f"Could not download file {path} from {bucket}") from e

def get_batch(batch_id: str) -> dict | None:
    try:
        result = _supabase_client.table('loyalty_batches').select('*').eq('id', batch_id).maybe_single().execute()
        return result.data
    except Exception as e:
        logger.error(f"Failed to get batch {batch_id}: {e}")
        raise RuntimeError(f"Could not retrieve batch {batch_id}") from e

def update_batch(batch_id: str, row_count: int | None, status: str):
    try:
        update_data = {"status": status}
        if row_count is not None:
            update_data["row_count"] = row_count
        
        _supabase_client.table('loyalty_batches').update(update_data).eq('id', batch_id).execute()
    except Exception as e:
        logger.error(f"Failed to update batch {batch_id}: {e}")
        raise RuntimeError(f"Could not update batch {batch_id}") from e

def update_batch_meta(batch_id: str, store_code: str, year_month: str):
    try:
        _supabase_client.table('loyalty_batches').update({
            "store_code": store_code,
            "year_month": year_month
        }).eq('id', batch_id).execute()
    except Exception as e:
        logger.error(f"Failed to update batch meta {batch_id}: {e}")
        raise RuntimeError(f"Could not update batch meta {batch_id}") from e

def check_existing_ingested_batch(batch_id: str, store_code: str, year_month: str) -> str | None:
    try:
        result = _supabase_client.table('loyalty_batches').select('id').eq('store_code', store_code).eq('year_month', year_month).eq('status', 'ingested').neq('id', batch_id).limit(1).execute()
        if result.data and len(result.data) > 0:
            return result.data[0]['id']
        return None
    except Exception as e:
        logger.error(f"Failed to check existing batch for {store_code} {year_month}: {e}")
        raise RuntimeError(f"Could not check existing batch") from e
